module.exports = {
    'adjacent-overload-signatures': true,
    'ban-ts-ignore': false,
    'ban-types': false,
    'member-access': [true, 'check-accessor', 'check-constructor', 'check-parameter-property'],
    'member-ordering': [
        true,
        {
            order: [
                'private-static-field',
                'protected-static-field',
                'public-static-field',
                'private-instance-field',
                'protected-instance-field',
                'public-instance-field',
                'private-constructor',
                'protected-constructor',
                'public-constructor',
                'private-static-method',
                'protected-static-method',
                'public-static-method',
                'private-instance-method',
                'protected-instance-method',
                'public-instance-method'
            ],
            alphabetize: true
        }
    ],
    'no-any': false,
    'no-empty-interface': true,
    'no-import-side-effect': [true, { 'ignore-module': '\\.(html|s[ca]ss|css)$' }],
    'no-inferrable-types': true,
    'no-internal-module': true,
    'no-magic-numbers': false,
    'no-namespace': [true, 'allow-declarations'],
    'no-non-null-assertion': true,
    'no-parameter-reassignment': true,
    'no-reference': true,
    'no-unnecessary-type-assertion': true,
    'no-var-requires': false,
    'only-arrow-functions': [true, 'allow-declarations', 'allow-named-functions'],
    'prefer-for-of': true,
    'promise-function-async': true,
    typedef: false,
    'typedef-whitespace': [
        true,
        {
            'call-signature': 'nospace',
            'index-signature': 'nospace',
            parameter: 'nospace',
            'property-declaration': 'nospace',
            'variable-declaration': 'nospace'
        },
        {
            'call-signature': 'onespace',
            'index-signature': 'onespace',
            parameter: 'onespace',
            'property-declaration': 'onespace',
            'variable-declaration': 'onespace'
        }
    ],
    'unified-signatures': true,
    'await-promise': true,
    'ban-comma-operator': true,
    ban: false,
    curly: [true, 'ignore-same-line'],
    forin: true,
    'function-constructor': true,
    'import-blacklist': false,
    'label-position': true,
    'no-arg': true,
    'no-bitwise': true,
    'no-conditional-assignment': true,
    'no-console': false,
    'no-construct': true,
    'no-debugger': true,
    'no-duplicate-super': true,
    'no-duplicate-switch-case': true,
    'no-duplicate-variable': [true, 'check-parameters'],
    'no-dynamic-delete': true,
    'no-empty': [true, 'allow-empty-catch', 'allow-empty-functions'],
    'no-eval': true,
    'no-floating-promises': true,
    'no-for-in-array': true,
    'no-implicit-dependencies': false,
    'no-inferred-empty-object-type': true,
    'no-invalid-template-strings': true,
    'no-invalid-this': [true, 'check-function-in-method'],
    'no-misused-new': true,
    'no-null-keyword': false,
    'no-object-literal-type-assertion': true,
    'no-return-await': true,
    'no-shadowed-variable': true,
    'no-sparse-arrays': true,
    'no-string-literal': true,
    'no-string-throw': true,
    'no-submodule-imports': false,
    'no-switch-case-fall-through': true,
    'no-this-assignment': [true, { 'allow-destructuring': true }],
    'no-unbound-method': [true, 'ignore-static'],
    'no-unnecessary-class': false,
    'no-unsafe-any': false,
    'no-unsafe-finally': true,
    'no-unused-expression': [true, 'allow-fast-null-checks', 'allow-tagged-template'],
    'no-use-before-declare': true,
    'no-var-keyword': true,
    'no-void-expression': [true, 'ignore-arrow-function-shorthand'],
    'prefer-conditional-expression': [true, 'check-if-else'],
    'prefer-object-spread': true,
    radix: true,
    'restrict-plus-operands': true,
    'strict-boolean-expressions': false,
    'strict-type-predicates': true,
    'switch-default': true,
    'triple-equals': true,
    'typeof-compare': false,
    'unnecessary-constructor': true,
    'use-default-type-parameter': true,
    'use-isnan': true,
    'cyclomatic-complexity': true,
    deprecation: true,
    eofline: true,
    indent: [true, 'spaces', 4],
    'linebreak-style': [true, 'LF'],
    'max-classes-per-file': [true, 1],
    'max-file-line-count': [true, 500],
    'max-line-length': [true, 120],
    'no-default-export': true,
    'no-default-import': false,
    'no-duplicate-imports': true,
    'no-mergeable-namespace': true,
    'no-require-imports': true,
    'object-literal-sort-keys': false,
    'prefer-const': [true, { destructuring: 'all' }],
    'prefer-readonly': true,
    'trailing-comma': [true, { multiline: 'never', singleline: 'never' }],
    align: false,
    'array-type': [true, 'array'],
    'arrow-parens': true,
    'arrow-return-shorthand': [true, 'multiline'],
    'binary-expression-operand-order': true,
    'callable-types': true,
    'class-name': true,
    'comment-format': [true, 'check-space'],
    'completed-docs': false,
    encoding: true,
    'file-header': false,
    'file-name-casing': [true, { '.tsx': 'pascal-case', '.ts': 'kebab-case' }],
    'import-spacing': true,
    'increment-decrement': false,
    'interface-name': false,
    'interface-over-type-literal': false,
    'jsdoc-format': [true, 'check-multiline-start'],
    'match-default-export-name': false,
    'newline-before-return': true,
    'newline-per-chained-call': false,
    'new-parens': true,
    'no-angle-bracket-type-assertion': true,
    'no-boolean-literal-compare': true,
    'no-consecutive-blank-lines': [true, 2],
    'no-irregular-whitespace': true,
    'no-parameter-properties': false,
    'no-redundant-jsdoc': true,
    'no-reference-import': true,
    'no-trailing-whitespace': true,
    'no-unnecessary-callback-wrapper': true,
    'no-unnecessary-initializer': true,
    'no-unnecessary-qualifier': true,
    'number-literal-format': true,
    'object-literal-key-quotes': [true, 'consistent-as-needed'],
    'object-literal-shorthand': true,
    'one-line': [true, 'check-catch', 'check-finally', 'check-else', 'check-open-brace', 'check-whitespace'],
    'one-variable-per-declaration': [true, 'ignore-for-loop'],
    'ordered-imports': [
        true,
        {
            'import-sources-order': 'case-insensitive',
            'named-imports-order': 'case-insensitive'
        }
    ],
    'prefer-function-over-method': false,
    'prefer-method-signature': true,
    'prefer-switch': [true, { 'min-cases': 4 }],
    'prefer-template': true,
    'prefer-while': true,
    quotemark: [true, 'single', 'jsx-single', 'avoid-template', 'avoid-escape'],
    'return-undefined': true,
    semicolon: [true, 'always', 'strict-bound-class-methods'],
    'space-before-function-paren': [true, 'always'],
    'space-within-parens': [true, 0],
    'switch-final-break': [true, 'always'],
    'type-literal-delimiter': true,
    'unnecessary-bind': true,
    'variable-name': [
        true,
        'ban-keywords',
        'check-format',
        'allow-leading-underscore',
        'allow-snake-case',
        'allow-trailing-underscore',
        'allow-pascal-case'
    ],
    whitespace: [
        true,
        'check-branch',
        'check-decl',
        'check-operator',
        'check-module',
        'check-separator',
        'check-rest-spread',
        'check-type',
        'check-typecast',
        'check-type-operator',
        'check-preblock',
        'check-postbrace'
    ]
};
